name: GoldenEcraftSKYWARS
version: 1.1-m16
description: SkyWars plugin
authors: [Wietje, andypandy89]
main: vc.pvp.skywars.SkyWars
depend: [WorldEdit, Vault]
softdepend: [Essentials, WhatIsIt, CommandHelper, Multiverse-Core, WorldGuard]

commands:
  skywars:
    aliases: [sw]
    description: Main command of the SkyWars plugin
  global:
    aliases: [g]
    description: Allows you to send a message to all players